In [ ]:
''' 


used financial data and ratios data saved to 'financial_ratios.parquet'

ratio data saved to 'ratio_data.parquet

'''

In [1]:
import pandas as pd

In [ ]:
financial_data=pd.read_parquet('financial_data.parquet')
df=financial_data.copy()

In [ ]:
used_features=['symbol',
               'report_date',
               '资产负债率',
               '经营活动净现金/销售收入',
               '营业总收入',
               '扣非净利润',
               '每股未分配利润',
               '净利润',
               '股东权益合计(净资产)',
               '每股净资产',
               '归母净利润',
               '每股现金流量净额']

In [ ]:
df_subset=df[used_features]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4099 entries, 0 to 4098
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   symbol        4099 non-null   object
 1   report_date   4099 non-null   datetime64[ns]
 2   资产负债率         4029 non-null   float64
 3   经营活动净现金/销售收入  3944 non-null   float64
 4   营业总收入         4091 non-null   float64
 5   扣非净利润         3807 non-null   float64
 6   每股未分配利润       3953 non-null   float64
 7   净利润           4093 non-null   float64
 8   股东权益合计(净资产)   4032 non-null   float64
 9   每股净资产         3976 non-null   float64
 10  归母净利润         4093 non-null   float64
 11  每股现金流量净额      3861 non-null   float64
dtypes: datetime64[ns](1), float64(10), object(1)
memory usage: 384.4+ KB

In [ ]:
print("Dataframe info:")
df_subset.info()
print('\n Dataframe description:')
df_subset.describe()

Dataframe info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4099 entries, 0 to 4098
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   symbol        4099 non-null   object
 1   report_date   4099 non-null   datetime64[ns]
 2   资产负债率         4029 non-null   float64
 3   经营活动净现金/销售收入  3944 non-null   float64
 4   营业总收入         4091 non-null   float64
 5   扣非净利润         3807 non-null   float64
 6   每股未分配利润       3953 non-null   float64
 7   净利润           4093 non-null   float64
 8   股东权益合计(净资产)   4032 non-null   float64
 9   每股净资产         3976 non-null   float64
 10  归母净利润         4093 non-null   float64
 11  每股现金流量净额      3861 non-null   float64
dtypes: datetime64[ns](1), float64(10), object(1)
memory usage: 384.4+ KB

 Dataframe description:

,report_date,资产负债率,经营活动净现金/销售收入,营业总收入,扣非净利润,每股未分配利润,净利润,股东权益合计(净资产),每股净资产,归母净利润,每股现金流量净额
count,4099,4029.000000,3944.000000,4.091000e+03,3.807000e+03,3953.000000,4.093000e+03,4.032000e+03,3976.000000,4.093000e+03,3861.000000
mean,2014-07-26 17:55:20.712368896,49.278310,-0.381071,8.479018e+10,6.544798e+09,5.226532,7.250269e+09,9.171171e+10,9.635094,6.508630e+09,0.349820
min,1992-12-31 00:00:00,1.929524,-550.335333,1.973082e+07,-2.440400e+10,-16.175629,-4.666233e+10,-2.906867e+10,-10.954416,-4.585998e+10,-23.910086
25%,2009-03-31 00:00:00,33.942665,0.016658,2.133225e+09,1.879346e+08,0.907067,1.946998e+08,4.124520e+09,3.194982,1.842881e+08,-0.268623
50%,2015-03-31 00:00:00,50.844601,0.122561,1.082270e+10,1.216892e+09,2.172392,1.319730e+09,2.090683e+10,5.626873,1.201452e+09,0.043173
75%,2020-09-30 00:00:00,62.937448,0.267844,4.939044e+10,5.097849e+09,4.574053,5.620703e+09,7.755968e+10,10.230383,5.051194e+09,0.499870
max,2025-09-30 00:00:00,229.013447,170.916374,3.318168e+12,1.480110e+11,168.394174,1.643650e+11,1.398894e+12,205.666530,1.494070e+11,37.763635
std,NaN,20.940641,15.458881,2.690594e+11,1.551294e+10,12.517409,1.714838e+10,1.953337e+11,15.471230,1.571584e+10,2.583569

In [ ]:
df['资产负债率'].isnull().sum()

np.int64(70)

In [39]:
#1.DE：total liablity/net worth
df['DE']=df['debt_ratio']*0.01/(1 - df['debt_ratio']*0.01)

In [ ]:
#2.NCOS:net cash from operation/sales
df['NCOS']=df['经营活动净现金/销售收入']

In [ ]:
#3.pretax net Non-operating income
df["PNNIS"]=df['扣非净利润']/df['营业总收入']

In [ ]:
#4. (net income -divid)/net income

df['NDN']=df['每股未分配利润']/(df['净利润']/(df["股东权益合计(净资产)"]/df['每股净资产']))

In [13]:
# 5. sales/total assets
df['STA']=df['营业总收入']/df['股东权益合计(净资产)']

In [ ]:
#6.ICSNW: net income -dividends/shareholder equity
df['ICSNW']=df['扣非净利润']/df['股东权益合计(净资产)']

In [ ]:
# 7.NITN: real net income to net income
df['NITN']=df['归母净利润']/df['净利润']

In [ ]:
#8.Cash per share
df['CASH_PER_SHARE']=df['每股现金流量净额']

In [ ]:
output_features=['DE',
                 'NCOS',
                 'PNNIS',
                 'NDN',
                 'STA',
                 'ICSNW',
                 'NITN',
                 'CASH_PER_SHARE']

In [ ]:
# rename used features
rename_dict = {
    '资产负债率': 'debt_ratio',
    '经营活动净现金/销售收入': 'op_cash_to_sales',
    '营业总收入': 'operating_revenue',
    '扣非净利润': 'net_profit_excl_extraordinary',
    '每股未分配利润': 'eps_retained_earnings',
    '净利润': 'net_profit',
    '股东权益合计(净资产)': 'total_equity',
    '每股净资产': 'eps_equity',
    '归母净利润': 'parent_net_profit',
    '每股现金流量净额': 'eps_cash_flow'
}
df = df.rename(columns=rename_dict)

In [ ]:
# after rename, basic features 
renamed_features = [
    'symbol',
    'report_date',
    'debt_ratio',
    'op_cash_to_sales',
    'operating_revenue',
    'net_profit_excl_extraordinary',
    'eps_retained_earnings',
    'net_profit',
    'total_equity',
    'eps_equity',
    'parent_net_profit',
    'eps_cash_flow'
]

In [ ]:
features=renamed_features+output_features

In [40]:
# contain all used features and ratios
output_df=df[features]

In [41]:
print('\n Output dataframe info:')
output_df.info()
print('\n output dataframe description')
output_df.describe()

 Output dataframe info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4099 entries, 0 to 4098
Data columns (total 20 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   symbol                         4099 non-null   object
 1   report_date                    4099 non-null   datetime64[ns]
 2   debt_ratio                     4029 non-null   float64
 3   op_cash_to_sales               3944 non-null   float64
 4   operating_revenue              4091 non-null   float64
 5   net_profit_excl_extraordinary  3807 non-null   float64
 6   eps_retained_earnings          3953 non-null   float64
 7   net_profit                     4093 non-null   float64
 8   total_equity                   4032 non-null   float64
 9   eps_equity                     3976 non-null   float64
 10  parent_net_profit              4093 non-null   float64
 11  eps_cash_flow                  3861 non-null   float64
 12  DE                             4029 non-null   float64
 13  NCOS                           3944 non-null   float64
 14  PNNIS                          3805 non-null   float64
 15  NDN                            3952 non-null   float64
 16  STA                            4027 non-null   float64
 17  ICSNW                          3790 non-null   float64
 18  NITN                           4093 non-null   float64
 19  CASH_PER_SHARE                 3861 non-null   float64
dtypes: datetime64[ns](1), float64(18), object(1)
memory usage: 640.6+ KB

 output dataframe description

,report_date,debt_ratio,op_cash_to_sales,operating_revenue,net_profit_excl_extraordinary,eps_retained_earnings,net_profit,total_equity,eps_equity,parent_net_profit,eps_cash_flow,DE,NCOS,PNNIS,NDN,STA,ICSNW,NITN,CASH_PER_SHARE
count,4099,4029.000000,3944.000000,4.091000e+03,3.807000e+03,3953.000000,4.093000e+03,4.032000e+03,3976.000000,4.093000e+03,3861.000000,4029.000000,3944.000000,3805.000000,3952.000000,4027.000000,3790.000000,4093.000000,3861.000000
mean,2014-07-26 17:55:20.712368896,49.278310,-0.381071,8.479018e+10,6.544798e+09,5.226532,7.250269e+09,9.171171e+10,9.635094,6.508630e+09,0.349820,1.770094,-0.381071,0.137303,10.712429,0.988843,0.079172,0.920330,0.349820
min,1992-12-31 00:00:00,1.929524,-550.335333,1.973082e+07,-2.440400e+10,-16.175629,-4.666233e+10,-2.906867e+10,-10.954416,-4.585998e+10,-23.910086,-3.905381,-550.335333,-0.575919,-359.195153,-1.331469,-0.703896,-4.812512,-23.910086
25%,2009-03-31 00:00:00,33.942665,0.016658,2.133225e+09,1.879346e+08,0.907067,1.946998e+08,4.124520e+09,3.194982,1.842881e+08,-0.268623,0.512635,0.016658,0.035699,2.220975,0.320750,0.025238,0.861603,-0.268623
50%,2015-03-31 00:00:00,50.844601,0.122561,1.082270e+10,1.216892e+09,2.172392,1.319730e+09,2.090683e+10,5.626873,1.201452e+09,0.043173,1.033356,0.122561,0.111650,4.221637,0.657835,0.063306,0.963270,0.043173
75%,2020-09-30 00:00:00,62.937448,0.267844,4.939044e+10,5.097849e+09,4.574053,5.620703e+09,7.755968e+10,10.230383,5.051194e+09,0.499870,1.696445,0.267844,0.207107,8.955101,1.230816,0.120423,1.000000,0.499870
max,2025-09-30 00:00:00,229.013447,170.916374,3.318168e+12,1.480110e+11,168.394174,1.643650e+11,1.398894e+12,205.666530,1.494070e+11,37.763635,58.562844,170.916374,0.670678,3223.659978,65.487354,0.648077,9.395935,37.763635
std,NaN,20.940641,15.458881,2.690594e+11,1.551294e+10,12.517409,1.714838e+10,1.953337e+11,15.471230,1.571584e+10,2.583569,3.273699,15.458881,0.138303,67.902848,1.577935,0.085356,0.356424,2.583569

In [42]:
output_df.to_parquet('financial_ratios.parquet', index=False)
print("\n used financial data and ratios data saved to 'financial_ratios.parquet'")

 used financial data and ratios data saved to 'financial_ratios.parquet'

In [43]:
ratio_df=df[['symbol','report_date']+output_features]

In [44]:
ratio_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4099 entries, 0 to 4098
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   symbol          4099 non-null   object
 1   report_date     4099 non-null   datetime64[ns]
 2   DE              4029 non-null   float64
 3   NCOS            3944 non-null   float64
 4   PNNIS           3805 non-null   float64
 5   NDN             3952 non-null   float64
 6   STA             4027 non-null   float64
 7   ICSNW           3790 non-null   float64
 8   NITN            4093 non-null   float64
 9   CASH_PER_SHARE  3861 non-null   float64
dtypes: datetime64[ns](1), float64(8), object(1)
memory usage: 320.4+ KB

In [45]:
ratio_df.to_parquet('ratio_data.parquet', index=False)
print("\n ratio data saved to 'ratio_data.parquet'")

 ratio data saved to 'ratio_data.parquet'